### ISSUE TITLE
inplace=False option doesn't work

### ISSUE THREAD

**Issue by werat** [DoozyX/clang-format-lint-action#18]
Setting `inplace: False` doesn't work and the action still works as if `inplace: True`.

```yaml
- uses: DoozyX/clang-format-lint-action@0.10
  with:
    inplace: False
```

This is because `--inplace` argument is defined as `type=bool` -- https://github.com/DoozyX/clang-format-lint-action/blob/v0.10/run-clang-format.py#L303

Everything is parsed as `bool`, expect for the empty string:

```python
In [1]: import argparse
   ...: parser = argparse.ArgumentParser()
   ...: parser.add_argument('-i', '--inplace', type=bool, default=False)
Out[1]: <...>

In [2]: parser.parse_args(['--inplace', 'True'])
Out[2]: Namespace(inplace=True)

In [3]: parser.parse_args(['--inplace', 'False'])
Out[3]: Namespace(inplace=True)

In [4]: parser.parse_args(['--inplace', '0'])
Out[4]: Namespace(inplace=True)

In [5]: parser.parse_args(['--inplace', ''])
Out[5]: Namespace(inplace=False)
```

So as a workaround one can set `inplace: ""`:

```yaml
- uses: DoozyX/clang-format-lint-action@0.10
  with:
    inplace: ""
```
