### ISSUE TITLE
option to save formatted files?

### ISSUE THREAD

**Issue by simonrenger** [DoozyX/clang-format-lint-action#4]
Is there a possibility that the formated files can be pushed as a new commit to the repository? That would be amazing and saves me time.

```
name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        save: true
        secrte: ...
        source: '.'
        exclude: './third_party'
        extensions: 'h,cpp'
        clangFormatVersion: 9
```
