### ISSUE TITLE
Please support `local` style

### ISSUE THREAD

**Issue by Hongbo-Miao** [DoozyX/clang-format-lint-action#47]
I have a `.clang-format` file.

When I use `local` for style:

```yaml
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: '.'
          extensions: 'c,cpp,h,ino'
          clangFormatVersion: 14
          style: local
```

I got error:

```sh
run-clang-format.py: error: Command '/clang-format/clang-format14 ./freertos/sketch/sketch.ino -style=local' returned non-zero exit status 1
Invalid value for -style
```

It would be great to support `local` for style. Thanks! 😊
