### ISSUE TITLE
Permission denied on v0.16 and clangFormat 16

### ISSUE THREAD

**Issue by ReenigneArcher** [DoozyX/clang-format-lint-action#58]
This step fails

```yml
      - name: Clang format lint
        if: ${{ steps.find_files.outputs.found_files }}
        uses: DoozyX/clang-format-lint-action@v0.16
        with:
          source: ${{ steps.find_files.outputs.found_files }}
          extensions: 'cpp,h,m,mm'
          clangFormatVersion: 16
          style: file
          inplace: false
```

With the following error. No other output.

`run-clang-format.py: error: Command '/clang-format/clang-format16 --version' failed to start: [Errno 13] Permission denied: '/clang-format/clang-format16'`

While this step will pass.

```yml
      - name: Clang format lint
        if: ${{ steps.find_files.outputs.found_files }}
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: ${{ steps.find_files.outputs.found_files }}
          extensions: 'cpp,h,m,mm'
          clangFormatVersion: 15
          style: file
          inplace: false
```
